import { useEffect, useState } from "react";
import "./App.css";
import Movie from "./components/Movie";
import SearchBar from "./components/SearchBar";

const API_KEY = process.env.REACT_APP_API_KEY; // API key generated by themoviedb.org
const BASE_URL = "https://api.themoviedb.org/3/";

function App() {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    const getMovies = async () => {
      await fetch(BASE_URL + "movie/popular?api_key=" + API_KEY)
        .then((resp) => resp.json())
        .then((data) => setMovies(data.results));
    };
    getMovies();
  }, []);

  const searchedQuery = async (data) => {
    await fetch(BASE_URL + "search/multi?api_key=" + API_KEY + "&query=" + data)
      .then((res) => res.json())
      .then((data) => setMovies(data.results));
  };

  return (
    <div className="app">
      <SearchBar searchedQuery={searchedQuery} />
      <div className="movie">
        {movies.map((movie) => (
          <Movie key={movie.id} info={movie} />
        ))}
      </div>
    </div>
  );
}

export default App;
